# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#

# Title and description of your site
title:          'Ari Glamslam'
description:    'Sie benötigen einen Webdesigner, Suchmaschinenoptimierer oder Social Media-Experten? Ari Glamslam bietet modernes Webdesign, SEO und Marketing.'
slogan:        	'Webdesign, Marketing & SEO'

# Build settings
url:          'http://phlow.github.io/ari-glamslam'
baseurl:      ''
urlimg:       'http://phlow.github.io/ari-glamslam/img/'
markdown:     kramdown
highlighter:  rouge
permalink:    /:categories/:title/
encoding:     utf-8

# Use <!--more--> in your posts to generate an excerpt and a teaser
excerpt_separator: <!--more-->



# The language setting is used in /includes/header.html for html-settings
language:       'de'



#      ______
#     / ____/__  ____ ___  _____
#    / / __/ _ \/ __ `__ \/ ___/
#   / /_/ /  __/ / / / / (__  )
#   \____/\___/_/ /_/ /_/____/
#
gems:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md

#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: post      # Set default layout to page
#  -
#    scope:
#      path: ''        # an empty string here means all files in the project
#      type: 'pages'
#    values:
#      layout: page      # Set default layout to page



#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed
